#!/bin/bash

###################
# File Management #
###################
git config --global alias.s status
git config --global alias.c commit
git config --global alias.po "push origin"
git config --global alias.fo "fetch origin"

###################
# Branch          #
###################

git config --global alias.b branch
git config --global alias.co checkout
git config --global alias.nb "checkout -b"
git config --global alias.db "branch -d"
git config --global alias.Db "branch -D"
git config --global alias.mb "branch -m"

###################
# Logging         #
###################
git config --global alias.l log
git config --global alias.lno "log --name-only"

###################
# Functions       #
###################
function gitclone() {
  git clone --quiet $2/${1}.git
}

function gitpullmaster() {
  git stash --quiet
  git co master --quiet
  git pull origin master:master -f
}
