#!/bin/bash

Z=${BASH_SOURCE[0]}

########################
# Grab latest version  #
########################
DIRNAME=$( builtin cd "$( dirname "$Z" )" && pwd )
     
pushd $DIRNAME >/dev/null 2>&1
git stash >/dev/null 2>&1
git checkout master >/dev/null 2>&1
git fetch origin master >/dev/null 2>&1

fetch="$(git diff --name-only origin/master)"
if [ -n "$fetch" ]; then
  git pull origin -f master >/dev/null 2>&1
  . $0
else
  . bash/shopts
  . bash/setupenv
  . bash/setupaliases
  . bash/mycd
  . bash/myvim
  export -f prplmnky_cd
  export -f vim
  export -f vi
  export -f togglepc
  . git/setupgit
fi

popd >/dev/null 2>&1

