#!/bin/bash

echo "sourced $(basename ${BASH_SOURCE[0]})"
########################
# Grab latest version  #
########################
DIRNAME=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
MYVERSION=1

cd $DIRNAME
git stash
git checkout master
git pull origin master

echo $1
echo "-z" [ -z $1 ]
if [ -z $1 ]; then
  if [ -e "version.txt" ]; then
  echo "-e" [ -e "version.text" ] $(cat "version.txt")
    if [ $MYVERSION -gt $(cat "version.txt") ]; then
      echo $(basename $0) $MYVERSION
      . $(basename $0) $MYVERSION
    fi
  else
      echo "2" $(basename $0) $MYVERSION
    . $(basename $0) $MYVERSION
  fi
fi

. bash/setupaliases
. git/setupgit

cd $OLDPWD
