#!/bin/bash

Z=${BASH_SOURCE[0]}
########################
# Grab latest version  #
########################
DIRNAME=$( cd "$( dirname "$Z" )" && pwd )
MYVERSION=1

cd $DIRNAME
git stash
git checkout master
git pull origin master

if [ -z $1 ]; then
  if [ -e "version.txt" ]; then
    if [ $MYVERSION -gt $(cat "version.txt") ]; then
      . $(basename $Z) $MYVERSION
    fi
  else
    . $(basename $Z) $MYVERSION
  fi
fi

. bash/setupaliases
. git/setupgit

cd $OLDPWD
