#!/bin/bash

#overwrite cd so that it recusively search the directories below until a
#match occurs.

function prplmnky_cd {
  if [ -z "$(declare -f prplmnky_old_cd)" ]; then
    if [ -n "$(declare -f cd)" ]; then
      eval "$(echo "prplmnky_old_cd()"; declare -f cd | tail -n +2)"
    else
      prplmnky_old_cd() { builtin cd $@; }
    fi
  fi

  export -f prplmnky_old_cd

  function cd() {
    prplmnky_old_cd $@ > /dev/null 2>&1
    v="$?"

    if [ $v -gt 0 ]; then
      for i in $@; do
        if [[ $i =~ ^-.*P.* ]]; then
          local noFollowSym=1
        fi
      done

      matches=($(find ${noFollowSym:-"-L"} . -maxdepth 5 -name "${@:$#:1}" -type d 2>/dev/null));

      if [ -n "${matches[0]}" ]; then
        prplmnky_old_cd ${@:1:$#-1} "${matches[0]}" &>/dev/null
        v="$?"
      fi
    
      if [ $v -gt 0 ]; then
        prplmnky_old_cd $@
      fi
    fi
  }

  export -f cd
}

prplmnky_cd

