#!/bin/bash

#escalate to root for files

function vim () 
{ 
    local vi_my_func_escalate=;
    until [[ $# -eq 0 ]]; do
        if [[ -e "$1" && ! -O "$1" ]]; then
            vi_my_func_escalate=1;
            break;
        fi;
        shift;
    done;
    if [ -n "$vi_my_func_escalate" ]; then
        sudo `which vim` $params;
    else
        command vim $params;
    fi
}

function vi() {
  vim "$@"
}
