#!/bin/bash


alias s=sudo
alias REBOOT="s reboot"

#############
# Package   #
#############

alias apti="s apt-get update; s apt-get install"
alias aptup="s apt-get update; s apt-get upgrade"
alias aptdup="s apt-get update; s apt-get dist-upgrade"
alias aptrm="s apt-get update; s apt-get remove"
alias aptp="s apt-get update; s apt-get remove --purge"
alias apts="s apt-get update; s apt-cache search"
alias bapti="s apt-build update; s apt-build install"
alias baptup="s apt-build update; s apt-build upgrade"
alias baptdup="s apt-build update; s apt-build dist-upgrade"
alias baptrm="s apt-build update; s apt-build remove"
alias baptp="s apt-build update; s apt-build remove --purge"
alias bapts="s apt-build update; s apt-build search"


#############
# Editor    #
#############
alias se="s -e"
alias v=vim
alias sv="s v"
