#!/bin/bash


alias s=sudo
alias REBOOT="s reboot"

#############
# Package   #
#############

alias aptup="s apt-get update; s apt-get upgrade"
alias aptdup="s apt-get update; s apt-get dist-upgrade"
alias aptrm="s apt-get update; s apt-get remove"
alias aptp="s apt-get update; s apt-get remove --purge"
alias baptup="s apt-build update; s apt-build upgrade"
alias baptdup="s apt-build update; s apt-build dist-upgrade"
alias baptrm="s apt-build update; s apt-build remove"
alias baptp="s apt-build update; s apt-build remove --purge"


#############
# Editor    #
#############
alias se="s -e"
alias svim="s vim"
alias VIM=svim
