#!/bin/bash

HOSTFILE=~/.hosts
function showls() {
  echo -en '\n\n********ls .'; for i in $(seq $(( $COLUMNS - 12 )) ) ; do echo -n '*'; done; ls; for i in $(seq $COLUMNS) ; do echo -n '*'; done;
}

PROMPT_COMMAND="showls"
